### ISSUE TITLE
Server bqmm-yjm$ node app-douban.js / app-meizitu.js报错

### ISSUE THREAD

**Issue by ontheway1215** [litt1e-p/weapp-girls#1]
请问Server bqmm-yjm$ node app-douban.js / app-meizitu.js一直报错是什么原因呢？

**Comment by litt1e-p** [comment]
node app-douban.js
node app-meizitu.js
choose one!

**Comment by ontheway1215** [comment]
but it still have some error
![image](https://cloud.githubusercontent.com/assets/11936847/20254233/6f67c2b6-aa6d-11e6-8179-25c4d0e3ebc2.png)

**Comment by litt1e-p** [comment]
@ontheway1215 check the package.json, there are some dependencies should be installed by npm
