### ISSUE TITLE
当我导入的时候 出现错误

### ISSUE THREAD

**Issue by swiftxy** [litt1e-p/weapp-girls#2]
Wed Nov 23 2016 17:18:50 GMT+0800 (CST) 读取 app.json 错误
VM315:2 app.json
未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。(anonymous function) @ VM315:2

**Comment by litt1e-p** [comment]
@yinjialiang1993 , please import project with path 'weapp-girls/App'
