### ISSUE TITLE
Error: ENOENT: no such file or directory, open './keys/server.key'

### ISSUE THREAD

**Issue by oikewll** [litt1e-p/weapp-girls#3]
这个怎么解决？ thx~
![image](https://cloud.githubusercontent.com/assets/244491/21843295/6906442a-d825-11e6-9c6a-2dd496f2be80.png)

**Comment by litt1e-p** [comment]
this blog will may do help [https](http://litt1e-p.github.io/2016/10/20/build-a-https-server-for-localhost/)

**Comment by oikewll** [comment]
多谢。再请教一个问题，https请求需要合法域名校验，你是怎么做的？

**Comment by litt1e-p** [comment]
@oikewll buy a domain name & https certification

**Comment by oikewll** [comment]
已解决。thanks again :)
