### ISSUE TITLE
这是什么问题怎么处理

### ISSUE THREAD

**Issue by JremeryHe** [litt1e-p/weapp-girls#4]
Thu May 25 2017 11:45:48 GMT+0800 (中国标准时间) 读取 app.json 错误
VM197:2 app.json
未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。
(anonymous function)

**Comment by litt1e-p** [comment]
@JremeryHe add it into your MINA dev tools with path 'yourProjectPath/weapp-girls/App' and run
