### ISSUE TITLE
nodejs Error: ENOENT: no such file or directory keys\ca.crt

### ISSUE THREAD

**Issue by FreeSlaver** [litt1e-p/weapp-girls#5]
你好，有bug
![image](https://user-images.githubusercontent.com/6946828/47129352-82d32280-d2c7-11e8-82c2-b4958d8d7bac.png)

**Comment by litt1e-p** [comment]
please read the [requirement](https://github.com/litt1e-p/weapp-girls#requirement) before using it, and [this article](http://blog.cpease.com/2016/10/20/build-a-https-server-for-localhost/) will be helpful
